apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor
  labels:
    app: harbor
spec:
  replicas: {{ .Values.harbor.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: harbor
  template:
    metadata:
      labels:
        app: harbor
    spec:
      containers:
        - name: harbor
          image: "{{ .Values.harbor.image.repository }}:{{ .Values.harbor.image.tag }}"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: harbor-data
              mountPath: /data
          resources:
            limits:
              cpu: "{{ .Values.harbor.resources.limits.cpu | default \"500m\" }}"
              memory: "{{ .Values.harbor.resources.limits.memory | default \"1Gi\" }}"
            requests:
              cpu: "{{ .Values.harbor.resources.requests.cpu | default \"250m\" }}"
              memory: "{{ .Values.harbor.resources.requests.memory | default \"512Mi\" }}"
      volumes:
        - name: harbor-data
          persistentVolumeClaim:
            claimName: harbor-pvc
