apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: harbor-ingress
  annotations:
    {{- toYaml .Values.harbor.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.harbor.ingress.className }}
  rules:
    {{- range .Values.harbor.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: harbor
                port:
                  number: 80
          {{- end }}
    {{- end }}
