apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-pv
spec:
  capacity:
    storage: {{ .Values.harbor.persistence.size }}
  accessModes:
    - {{ .Values.harbor.persistence.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.harbor.persistence.storageClass }}
  hostPath:
    path: "/mnt/data/harbor"
