apiVersion: v1
kind: Service
metadata:
  name: harbor
spec:
  type: {{ .Values.harbor.service.type }}
  ports:
    - port: {{ .Values.harbor.service.port }}
      targetPort: 80
  selector:
    app: harbor
